Feature/stock adaptivecard
Cognigy/Extensions pull request #85
Opened 2021-05-06 21:40 UTC by antonxt

Hi @AlexTeusz,

Can you review my new extension and merge it with master if everything is fine? I will then create a release.

Thank you!

2021-05-11 13:08 UTC, AlexTeusz requested changes

2021-05-11 13:08 UTC, alexteusz commented on extensions/blueprism/README.md
> +**Secret (Blue Prism):**
Please rename to Connection

2021-05-11 13:08 UTC, alexteusz commented on extensions/blueprism/README.md
> +1. `username` Blue Prism user name, e.g. admin
Please explain where to find the values in BluePrism

2021-05-11 13:08 UTC, alexteusz commented on extensions/blueprism/README.md
> +## Node: startBlueprismProcess
The name has not the same pattern to the others. Should it be called **Start Process** ?

2021-05-11 13:08 UTC, alexteusz commented on extensions/blueprism/package.json
> +  "version": "1.0.0",
version should be 4.0.0

2021-05-11 13:08 UTC, alexteusz commented on extensions/blueprism/package.json
> +  "keywords": [
Please use Blueprism related keywords, such as "RPA", "Robot", "Process", "Automation"

2021-05-11 13:08 UTC, alexteusz commented on extensions/blueprism/package.json
> +    "@cognigy/extension-tools": "^0.10.0",
Please use version 0.11.0 of the extension-tools

2021-05-11 13:08 UTC, alexteusz commented on extensions/blueprism/src/nodes/startBlueprismProcess.ts
> +    axios({
Please use try catch block with async await such as in other extensions

2021-05-11 13:08 UTC, alexteusz commented on extensions/blueprism/src/nodes/startBlueprismProcess.ts
> +      store('test test test');
I think that test test test should be removed, right?

2021-05-11 13:08 UTC, alexteusz commented on extensions/stock-adaptivecard/package.json
> +  "version": "1.0.0",
Version should be 4.0.0

2021-05-11 13:08 UTC, alexteusz commented on extensions/stock-adaptivecard/package.json
> +    "Cognigy.AI",
Please use stock related keywords

2021-05-11 13:08 UTC, alexteusz commented on extensions/stock-adaptivecard/package.json
> +    "@cognigy/extension-tools": "^0.10.0",
Please use version 0.11.0 of the extension-tools

2021-05-11 13:49 UTC, antonxt commented on extensions/blueprism/README.md
> +1. `username` Blue Prism user name, e.g. admin
The blueprism code got into this branch by mistake. I am removing it completely. Will create another pull request when the blueprism branch is ready

2021-05-11 13:50 UTC, antonxt commented on extensions/blueprism/README.md
> +## Node: startBlueprismProcess
The blueprism code got into this branch by mistake. I am removing it completely. Will create another pull request when the blueprism branch is ready

2021-05-11 13:50 UTC, antonxt commented on extensions/blueprism/package.json
> +  "version": "1.0.0",
The blueprism code got into this branch by mistake. I am removing it completely. Will create another pull request when the blueprism branch is ready

2021-05-11 13:50 UTC, antonxt commented on extensions/blueprism/package.json
> +  "keywords": [
The blueprism code got into this branch by mistake. I am removing it completely. Will create another pull request when the blueprism branch is ready

2021-05-11 13:50 UTC, antonxt commented on extensions/blueprism/package.json
> +    "@cognigy/extension-tools": "^0.10.0",
The blueprism code got into this branch by mistake. I am removing it completely. Will create another pull request when the blueprism branch is ready

2021-05-11 13:52 UTC, antonxt commented on extensions/blueprism/src/nodes/startBlueprismProcess.ts
> +      store('test test test');
The blueprism code got into this branch by mistake. I am removing it completely. Will create another pull request when the blueprism branch is ready

2021-05-11 13:53 UTC, antonxt commented on extensions/blueprism/src/nodes/startBlueprismProcess.ts
> +    axios({
The blueprism code got into this branch by mistake. I am removing it completely. Will create another pull request when the blueprism branch is ready

2021-05-12 10:38 UTC, AlexTeusz approved these changes

2021-05-12 10:38 UTC, merged